### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined after the 2.8.1 release

### ISSUE THREAD

**Issue by alexmicic** [alma/widgets#57]
After the 2.8.1 release I am seeing this error when trying to init the Alma Widget:
widgets.umd.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at widgets.umd.js:1:584
    at widgets.umd.js:1:416
    at widgets.umd.js:1:535

Before it was working fine.

Thanks.

**Comment by gautierlabarre** [comment]
Hello, sorry for the delay do you still have the issue with versions above 2.8.3 ?

**Comment by gautierlabarre** [comment]
Hello, sorry for the delay do you still have the issue with versions above 2.8.3 ?

**Comment by alexmicic** [comment]
Hi, no problem. It works fine now. Thanks
