### ISSUE TITLE
Shopify – Trigger Re-Render on Variant Change

### ISSUE THREAD

**Issue by butterydev** [alma/widgets#62]
The old API had a "render" method. On variant change, I used this to trigger a re-render of the widget with the selected variant details.

Is there a way to do this with this new API??? .... I'm not seeing it in the source.

Thank you!!!

**Comment by gautierlabarre** [comment]
Hello,

You have an example of re-rendering the widget in the `basic.html` example.
When you change the **quantity** with the **select field**, you can call the method that `add` the widget. This will refresh the widget with the new properties.

**Comment by butterydev** [comment]
Awesome!!! Thank you!!! Can you point me to where the basic.html example is?

Thanks again!!!

**Comment by gautierlabarre** [comment]
You have all examples on this folder : https://github.com/alma/widgets/tree/master/examples

**Comment by butterydev** [comment]
THANKS AGAIN!!!
